package cs340.game.shared;

public enum City {
    VANCOUVER, SEATTLE, PORTLAND, SAN_FRANCISCO, LOS_ANGELES, CALGARY, HELENA, SALT_LAKE_CITY,
    LAS_VEGAS, DENVER, SANTA_FE, PHOENIX, EL_PASO, WINNIPEG, DULUTH, OMAHA, KANSAS_CITY,
    OKLAHOMA_CITY, DALLAS, HOUSTON, SAULT_ST_MARIE, CHICAGO, SAINT_LOUIS, LITTLE_ROCK, NEW_ORLEANS,
    MONTREAL, TORONTO, PITTSBURGH, NASHVILLE, ATLANTA, BOSTON, NEW_YORK, WASHINGTON, RALEIGH,
    CHARLESTON, MIAMI
}
