package cs340.game.shared;

public enum CommandType {
    LOGIN, REGISTER, CREATE_GAME, JOIN_GAME, START_GAME, LOBBY_POLL, GAME_POLL,
    DRAW_TRAIN_CARD_DECK, DRAW_TRAIN_CARD_FACE_UP, DRAW_DESTINATION_CARD, DISCARD_TRAIN_CARD,
    DISCARD_DESTINATION_CARD, CHAT
}
